In [11]:
import pandas as pd
import glob

path = 'OTP by month' # use your path
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

frame = pd.concat(li, axis=0, ignore_index=True, sort=True)

frame.drop(columns='Unnamed: 12')

,Unnamed: 0,cancelled_numerator,gtfs_route_desc,gtfs_route_id,gtfs_route_long_name,gtfs_route_short_name,metric_type,mode_type,otp_denominator,otp_numerator,peak_offpeak_ind,route_category,service_date
0,NaN,NaN,Rapid Transit,Red,Red Line,NaN,Passenger Wait Time,Rail,45276.489510,33862.267130,OFF_PEAK,Red Line,2018-12-01
1,NaN,NaN,Rapid Transit,Orange,Orange Line,NaN,Passenger Wait Time,Rail,68989.753150,64710.364490,OFF_PEAK,Orange Line,2018-12-01
2,NaN,NaN,Rapid Transit,Green-B,Green Line B,B,Passenger Wait Time,Rail,18071.489450,13614.234600,OFF_PEAK,Green Line,2018-12-01
3,NaN,NaN,Rapid Transit,Green-C,Green Line C,C,Passenger Wait Time,Rail,21404.877910,16129.840480,OFF_PEAK,Green Line,2018-12-01
4,NaN,NaN,Rapid Transit,Green-D,Green Line D,D,Passenger Wait Time,Rail,5513.485726,3806.540713,OFF_PEAK,Green Line,2018-12-01
5,NaN,NaN,Rapid Transit,Green-E,Green Line E,E,Passenger Wait Time,Rail,30424.189410,24608.791490,OFF_PEAK,Green Line,2018-12-01
6,NaN,NaN,Rapid Transit,Blue,Blue Line,NaN,Passenger Wait Time,Rail,40898.437720,38677.860880,OFF_PEAK,Blue Line,2018-12-01
7,NaN,NaN,Rapid Transit,741,Silver Line SL1,SL1,Headway / Schedule Adherence,Bus,1225.000000,935.000000,OFF_PEAK,Silver Line,2018-12-01
8,NaN,NaN,Rapid Transit,742,Silver Line SL2,SL2,Headway / Schedule Adherence,Bus,503.000000,345.000000,OFF_PEAK,Silver Line,2018-12-01
9,NaN,NaN,Rapid Transit,751,Silver Line SL4,SL4,Headway / Schedule Adherence,Bus,1274.000000,909.000000,OFF_PEAK,Silver Line,2018-12-01
10,NaN,NaN,Rapid Transit,749,Silver Line SL5,SL5,Headway / Schedule Adherence,Bus,2826.000000,2140.000000,OFF_PEAK,Silver Line,2018-12-01
11,NaN,0.0,Commuter Rail,CR-Fairmount,Fairmount Line,NaN,Headway / Schedule Adherence,Commuter Rail,32.000000,32.000000,OFF_PEAK,NaN,2018-12-01
12,NaN,0.0,Commuter Rail,CR-Fairmount,Fairmount Line,NaN,Headway / Schedule Adherence,Commuter Rail,0.000000,0.000000,PEAK,NaN,2018-12-01
13,NaN,0.0,Commuter Rail,CR-Fitchburg,Fitchburg Line,NaN,Headway / Schedule Adherence,Commuter Rail,0.000000,0.000000,PEAK,NaN,2018-12-01
14,NaN,0.0,Commuter Rail,CR-Fitchburg,Fitchburg Line,NaN,Headway / Schedule Adherence,Commuter Rail,15.000000,11.000000,OFF_PEAK,NaN,2018-12-01
15,NaN,0.0,Commuter Rail,CR-Worcester,Framingham/Worcester Line,NaN,Headway / Schedule Adherence,Commuter Rail,19.000000,18.000000,OFF_PEAK,NaN,2018-12-01
16,NaN,0.0,Commuter Rail,CR-Worcester,Framingham/Worcester Line,NaN,Headway / Schedule Adherence,Commuter Rail,0.000000,0.000000,PEAK,NaN,2018-12-01
17,NaN,0.0,Commuter Rail,CR-Franklin,Franklin Line,NaN,Headway / Schedule Adherence,Commuter Rail,18.000000,18.000000,OFF_PEAK,NaN,2018-12-01
18,NaN,0.0,Commuter Rail,CR-Franklin,Franklin Line,NaN,Headway / Schedule Adherence,Commuter Rail,0.000000,0.000000,PEAK,NaN,2018-12-01
19,NaN,0.0,Commuter Rail,CR-Greenbush,Greenbush Line,NaN,Headway / Schedule Adherence,Commuter Rail,16.000000,12.000000,OFF_PEAK,NaN,2018-12-01
20,NaN,0.0,Commuter Rail,CR-Greenbush,Greenbush Line,NaN,Headway / Schedule Adherence,Commuter Rail,0.000000,0.000000,PEAK,NaN,2018-12-01
21,NaN,0.0,Commuter Rail,CR-Haverhill,Haverhill Line,NaN,Headway / Schedule Adherence,Commuter Rail,13.000000,13.000000,OFF_PEAK,NaN,2018-12-01
22,NaN,0.0,Commuter Rail,CR-Haverhill,Haverhill Line,NaN,Headway / Schedule Adherence,Commuter Rail,0.000000,0.000000,PEAK,NaN,2018-12-01
23,NaN,0.0,Commuter Rail,CR-Kingston,Kingston/Plymouth Line,NaN,Headway / Schedule Adherence,Commuter Rail,16.000000,16.000000,OFF_PEAK,NaN,2018-12-01
24,NaN,0.0,Commuter Rail,CR-Kingston,Kingston/Plymouth Line,NaN,Headway / Schedule Adherence,Commuter Rail,0.000000,0.000000,PEAK,NaN,2018-12-01
25,NaN,0.0,Commuter Rail,CR-Lowell,Lowell Line,NaN,Headway / Schedule Adherence,Commuter Rail,0.000000,0.000000,PEAK,NaN,2018-12-01
26,NaN,0.0,Commuter Rail,CR-Lowell,Lowell Line,NaN,Headway / Schedule Adherence,Commuter Rail,1.000000,1.000000,OFF_PEAK,NaN,2018-12-01
27,NaN,0.0,Commuter Rail,CR-Middleborough,Middleborough/Lakeville Line,NaN,Headway / Schedule Adherence,Commuter Rail,16.000000,15.000000,OFF_PEAK,NaN,2018-12-01
28,NaN,0.0,Commuter Rail,CR-Middleborough,Middleborough/Lakeville Line,NaN,Headway / Schedule Adherence,Commuter Rail,0.000000,0.000000,PEAK,NaN,2018-12-01
29,NaN,0.0,Commuter Rail,CR-Needham,Needham Line,NaN,Headway / Schedule Adherence,Commuter Rail,18.000000,16.000000,OFF_PEAK,NaN,2018-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112350,NaN,NaN,Express Bus,450,NaN,450,Headway / Schedule Adherence,Bus,289.000000,174.000000,OFF_PEAK,Other Bus,2018-04-30
112351,NaN,NaN,Express Bus,450,NaN,450,Headway / Schedule Adherence,Bus,135.000000,65.000000,PEAK,Other Bus,2018-04-30
112352,NaN,NaN,Limited Service,451,NaN,451,Headway / Schedule Adherence,Bus,43.000000,33.000000,OFF_PEAK,Other Bus,2018-04-30
112353,NaN,NaN,Limited Service,451,NaN,451,Headway / Schedule Adherence,Bus,53.000000,38.000000,PEAK,Other Bus,2018-04-30
112354,NaN,NaN,Local Bus,455,NaN,455,Headway / Schedule Adherence,Bus,120.000000,60.000000,PEAK,Other Bus,2018-04-30
112355,NaN,NaN,Local Bus,455,NaN,455,Headway / Schedule Adherence,Bus,349.000000,239.000000,OFF_PEAK,Other Bus,2018-04-30
112356,NaN,NaN,Limited Service,456,NaN,456,Headway / Schedule Adherence,Bus,12.000000,11.000000,PEAK,Other Bus,2018-04-30
112357,NaN,NaN,Limited Service,456,NaN,456,Headway / Schedule Adherence,Bus,64.000000,52.000000,OFF_PEAK,Other Bus,2018-04-30
112358,NaN,NaN,Express Bus,459,NaN,459,Headway / Schedule Adherence,Bus,213.000000,117.000000,OFF_PEAK,Other Bus,2018-04-30
112359,NaN,NaN,Express Bus,459,NaN,459,Headway / Schedule Adherence,Bus,77.000000,29.000000,PEAK,Other Bus,2018-04-30
112360,NaN,NaN,Local Bus,465,NaN,465,Headway / Schedule Adherence,Bus,84.000000,50.000000,OFF_PEAK,Other Bus,2018-04-30
112361,NaN,NaN,Local Bus,465,NaN,465,Headway / Schedule Adherence,Bus,31.000000,19.000000,PEAK,Other Bus,2018-04-30
112362,NaN,NaN,Express Bus,501,NaN,501,Headway / Schedule Adherence,Bus,122.000000,80.000000,PEAK,Other Bus,2018-04-30
112363,NaN,NaN,Express Bus,501,NaN,501,Headway / Schedule Adherence,Bus,61.000000,45.000000,OFF_PEAK,Other Bus,2018-04-30
112364,NaN,NaN,Express Bus,502,NaN,502,Headway / Schedule Adherence,Bus,167.000000,137.000000,PEAK,Other Bus,2018-04-30
112365,NaN,NaN,Express Bus,502,NaN,502,Headway / Schedule Adherence,Bus,32.000000,28.000000,OFF_PEAK,Other Bus,2018-04-30
112366,NaN,NaN,Express Bus,503,NaN,503,Headway / Schedule Adherence,Bus,15.000000,8.000000,OFF_PEAK,Other Bus,2018-04-30
112367,NaN,NaN,Express Bus,503,NaN,503,Headway / Schedule Adherence,Bus,56.000000,45.000000,PEAK,Other Bus,2018-04-30
112368,NaN,NaN,Express Bus,504,NaN,504,Headway / Schedule Adherence,Bus,222.000000,141.000000,PEAK,Other Bus,2018-04-30
112369,NaN,NaN,Express Bus,504,NaN,504,Headway / Schedule Adherence,Bus,250.000000,164.000000,OFF_PEAK,Other Bus,2018-04-30
112370,NaN,NaN,Express Bus,505,NaN,505,Headway / Schedule Adherence,Bus,158.000000,116.000000,OFF_PEAK,Other Bus,2018-04-30
112371,NaN,NaN,Express Bus,505,NaN,505,Headway / Schedule Adherence,Bus,249.000000,145.000000,PEAK,Other Bus,2018-04-30
112372,NaN,NaN,Express Bus,553,NaN,553,Headway / Schedule Adherence,Bus,172.000000,97.000000,OFF_PEAK,Other Bus,2018-04-30
112373,NaN,NaN,Express Bus,553,NaN,553,Headway / Schedule Adherence,Bus,62.000000,32.000000,PEAK,Other Bus,2018-04-30
112374,NaN,NaN,Express Bus,554,NaN,554,Headway / Schedule Adherence,Bus,59.000000,32.000000,PEAK,Other Bus,2018-04-30
112375,NaN,NaN,Express Bus,554,NaN,554,Headway / Schedule Adherence,Bus,122.000000,70.000000,OFF_PEAK,Other Bus,2018-04-30
112376,NaN,NaN,Express Bus,556,NaN,556,Headway / Schedule Adherence,Bus,61.000000,45.000000,OFF_PEAK,Other Bus,2018-04-30
112377,NaN,NaN,Express Bus,556,NaN,556,Headway / Schedule Adherence,Bus,61.000000,24.000000,PEAK,Other Bus,2018-04-30
112378,NaN,NaN,Express Bus,558,NaN,558,Headway / Schedule Adherence,Bus,61.000000,34.000000,PEAK,Other Bus,2018-04-30
112379,NaN,NaN,Express Bus,558,NaN,558,Headway / Schedule Adherence,Bus,43.000000,32.000000,OFF_PEAK,Other Bus,2018-04-30

In [12]:
#filters

filter1 = frame['gtfs_route_id'] == "1"

filter2 = frame['gtfs_route_id'] == "43"

filter3 = frame['gtfs_route_id'] == "749"

filter4 = frame['gtfs_route_id'] == "751"

In [13]:
frame.where(filter1 | filter2 | filter3 | filter4, inplace = True)

frame_ColumnsNeeded = frame[["gtfs_route_id","service_date","peak_offpeak_ind","otp_numerator","otp_denominator"]].dropna()

frameFinal = (frame_ColumnsNeeded[pd.notnull(frame_ColumnsNeeded[["gtfs_route_id","service_date","peak_offpeak_ind","otp_numerator","otp_denominator"]])]).sort_values(by=['service_date']).reset_index().drop(columns="index")

In [14]:
frameFinal

,gtfs_route_id,service_date,peak_offpeak_ind,otp_numerator,otp_denominator
0,751,2018-01-01,OFF_PEAK,818.0,1012.0
1,43,2018-01-01,OFF_PEAK,314.0,394.0
2,749,2018-01-01,OFF_PEAK,1836.0,2195.0
3,1,2018-01-01,OFF_PEAK,689.0,1183.0
4,43,2018-01-02,OFF_PEAK,244.0,350.0
5,43,2018-01-02,PEAK,111.0,140.0
6,1,2018-01-02,OFF_PEAK,1136.0,1398.0
7,751,2018-01-02,OFF_PEAK,936.0,1142.0
8,749,2018-01-02,PEAK,611.0,689.0
9,749,2018-01-02,OFF_PEAK,1779.0,2039.0
10,751,2018-01-02,PEAK,301.0,361.0
11,1,2018-01-02,PEAK,418.0,556.0
12,751,2018-01-03,OFF_PEAK,886.0,1197.0
13,751,2018-01-03,PEAK,321.0,394.0
14,749,2018-01-03,OFF_PEAK,1713.0,2182.0
15,749,2018-01-03,PEAK,681.0,852.0
16,1,2018-01-03,PEAK,255.0,421.0
17,1,2018-01-03,OFF_PEAK,838.0,1239.0
18,43,2018-01-03,PEAK,59.0,140.0
19,43,2018-01-03,OFF_PEAK,219.0,352.0
20,43,2018-01-04,OFF_PEAK,205.0,316.0
21,43,2018-01-04,PEAK,54.0,94.0
22,1,2018-01-04,PEAK,366.0,477.0
23,1,2018-01-04,OFF_PEAK,939.0,1196.0
24,751,2018-01-04,PEAK,352.0,402.0
25,751,2018-01-04,OFF_PEAK,853.0,1054.0
26,749,2018-01-04,PEAK,476.0,605.0
27,749,2018-01-04,OFF_PEAK,1528.0,1875.0
28,751,2018-01-05,OFF_PEAK,878.0,1118.0
29,751,2018-01-05,PEAK,172.0,289.0
...,...,...,...,...,...
2442,43,2018-12-26,PEAK,86.0,128.0
2443,43,2018-12-26,OFF_PEAK,266.0,356.0
2444,1,2018-12-27,OFF_PEAK,1503.0,1878.0
2445,43,2018-12-27,OFF_PEAK,319.0,462.0
2446,751,2018-12-27,OFF_PEAK,1638.0,1897.0
2447,749,2018-12-27,OFF_PEAK,2505.0,2994.0
2448,43,2018-12-28,OFF_PEAK,257.0,336.0
2449,751,2018-12-28,PEAK,392.0,497.0
2450,751,2018-12-28,OFF_PEAK,1173.0,1396.0
2451,749,2018-12-28,PEAK,634.0,767.0
2452,749,2018-12-28,OFF_PEAK,1770.0,2215.0
2453,1,2018-12-28,OFF_PEAK,1000.0,1291.0
2454,1,2018-12-28,PEAK,378.0,484.0
2455,43,2018-12-28,PEAK,92.0,129.0
2456,751,2018-12-29,OFF_PEAK,1183.0,1558.0
2457,749,2018-12-29,OFF_PEAK,2394.0,3228.0
2458,1,2018-12-29,OFF_PEAK,1210.0,1603.0
2459,43,2018-12-29,OFF_PEAK,278.0,504.0
2460,751,2018-12-30,OFF_PEAK,1259.0,1568.0
2461,749,2018-12-30,OFF_PEAK,2281.0,3005.0
2462,43,2018-12-30,OFF_PEAK,279.0,411.0
2463,1,2018-12-30,OFF_PEAK,849.0,1164.0
2464,43,2018-12-31,OFF_PEAK,199.0,311.0
2465,43,2018-12-31,PEAK,86.0,122.0
2466,1,2018-12-31,PEAK,323.0,411.0
2467,1,2018-12-31,OFF_PEAK,903.0,1199.0
2468,751,2018-12-31,OFF_PEAK,1080.0,1368.0
2469,749,2018-12-31,OFF_PEAK,1744.0,2260.0
2470,751,2018-12-31,PEAK,428.0,498.0
2471,749,2018-12-31,PEAK,650.0,780.0

In [19]:
OTP_for_the_day = frameFinal["otp_numerator"]/frameFinal["otp_denominator"]
frameFinal["Headway Analysis (Schedule Adherence) Score"]= OTP_for_the_day
frameFinal

,gtfs_route_id,service_date,peak_offpeak_ind,otp_numerator,otp_denominator,Headway Analysis (Schedule Adherence) Score
0,751,2018-01-01,OFF_PEAK,818.0,1012.0,0.808300
1,43,2018-01-01,OFF_PEAK,314.0,394.0,0.796954
2,749,2018-01-01,OFF_PEAK,1836.0,2195.0,0.836446
3,1,2018-01-01,OFF_PEAK,689.0,1183.0,0.582418
4,43,2018-01-02,OFF_PEAK,244.0,350.0,0.697143
5,43,2018-01-02,PEAK,111.0,140.0,0.792857
6,1,2018-01-02,OFF_PEAK,1136.0,1398.0,0.812589
7,751,2018-01-02,OFF_PEAK,936.0,1142.0,0.819615
8,749,2018-01-02,PEAK,611.0,689.0,0.886792
9,749,2018-01-02,OFF_PEAK,1779.0,2039.0,0.872487
10,751,2018-01-02,PEAK,301.0,361.0,0.833795
11,1,2018-01-02,PEAK,418.0,556.0,0.751799
12,751,2018-01-03,OFF_PEAK,886.0,1197.0,0.740184
13,751,2018-01-03,PEAK,321.0,394.0,0.814721
14,749,2018-01-03,OFF_PEAK,1713.0,2182.0,0.785060
15,749,2018-01-03,PEAK,681.0,852.0,0.799296
16,1,2018-01-03,PEAK,255.0,421.0,0.605701
17,1,2018-01-03,OFF_PEAK,838.0,1239.0,0.676352
18,43,2018-01-03,PEAK,59.0,140.0,0.421429
19,43,2018-01-03,OFF_PEAK,219.0,352.0,0.622159
20,43,2018-01-04,OFF_PEAK,205.0,316.0,0.648734
21,43,2018-01-04,PEAK,54.0,94.0,0.574468
22,1,2018-01-04,PEAK,366.0,477.0,0.767296
23,1,2018-01-04,OFF_PEAK,939.0,1196.0,0.785117
24,751,2018-01-04,PEAK,352.0,402.0,0.875622
25,751,2018-01-04,OFF_PEAK,853.0,1054.0,0.809298
26,749,2018-01-04,PEAK,476.0,605.0,0.786777
27,749,2018-01-04,OFF_PEAK,1528.0,1875.0,0.814933
28,751,2018-01-05,OFF_PEAK,878.0,1118.0,0.785331
29,751,2018-01-05,PEAK,172.0,289.0,0.595156
...,...,...,...,...,...,...
2442,43,2018-12-26,PEAK,86.0,128.0,0.671875
2443,43,2018-12-26,OFF_PEAK,266.0,356.0,0.747191
2444,1,2018-12-27,OFF_PEAK,1503.0,1878.0,0.800319
2445,43,2018-12-27,OFF_PEAK,319.0,462.0,0.690476
2446,751,2018-12-27,OFF_PEAK,1638.0,1897.0,0.863469
2447,749,2018-12-27,OFF_PEAK,2505.0,2994.0,0.836673
2448,43,2018-12-28,OFF_PEAK,257.0,336.0,0.764881
2449,751,2018-12-28,PEAK,392.0,497.0,0.788732
2450,751,2018-12-28,OFF_PEAK,1173.0,1396.0,0.840258
2451,749,2018-12-28,PEAK,634.0,767.0,0.826597
2452,749,2018-12-28,OFF_PEAK,1770.0,2215.0,0.799097
2453,1,2018-12-28,OFF_PEAK,1000.0,1291.0,0.774593
2454,1,2018-12-28,PEAK,378.0,484.0,0.780992
2455,43,2018-12-28,PEAK,92.0,129.0,0.713178
2456,751,2018-12-29,OFF_PEAK,1183.0,1558.0,0.759307
2457,749,2018-12-29,OFF_PEAK,2394.0,3228.0,0.741636
2458,1,2018-12-29,OFF_PEAK,1210.0,1603.0,0.754835
2459,43,2018-12-29,OFF_PEAK,278.0,504.0,0.551587
2460,751,2018-12-30,OFF_PEAK,1259.0,1568.0,0.802934
2461,749,2018-12-30,OFF_PEAK,2281.0,3005.0,0.759068
2462,43,2018-12-30,OFF_PEAK,279.0,411.0,0.678832
2463,1,2018-12-30,OFF_PEAK,849.0,1164.0,0.729381
2464,43,2018-12-31,OFF_PEAK,199.0,311.0,0.639871
2465,43,2018-12-31,PEAK,86.0,122.0,0.704918
2466,1,2018-12-31,PEAK,323.0,411.0,0.785888
2467,1,2018-12-31,OFF_PEAK,903.0,1199.0,0.753128
2468,751,2018-12-31,OFF_PEAK,1080.0,1368.0,0.789474
2469,749,2018-12-31,OFF_PEAK,1744.0,2260.0,0.771681
2470,751,2018-12-31,PEAK,428.0,498.0,0.859438
2471,749,2018-12-31,PEAK,650.0,780.0,0.833333

In [21]:
frameFinal.to_csv("OTP by month/Full_List_of_ChesterSquare_stops_OTPs.csv")