In [1]:
import pandas as pd

In [8]:
shapesdf = pd.read_csv("MBTA_GTFS_csv/shapes.csv")

shapes = pd.DataFrame(shapesdf).drop(columns='Unnamed: 0')

In [9]:
trips = pd.read_csv("MBTA_GTFS_csv/trips.csv")

/Users/arimayer/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [10]:
routes = pd.read_csv("MBTA_GTFS_csv/routes.csv")

In [12]:
stops = pd.read_csv("MBTA_GTfS_csv/stops.csv")

In [14]:
#Route 1 line with its coinciding shapeID
filter1 = shapes['shape_id']=='010058'

#Route 43 with its coinciding shapeID
filter2 = shapes['shape_id']=='430031'

#Route SL5 with its coinciding shapeID
filter3 = shapes['shape_id']=='7490022'

#Route SL4 with its coinciding shapeID
filter4 = shapes['shape_id']=='7510024'

In [37]:
shapes.where(filter1 | filter2 | filter3 | filter4, inplace = True)

In [56]:
newshapesdf = shapes[['shape_id','shape_pt_lat','shape_pt_lon']].dropna()
newnew = newshapesdf[pd.notnull(newshapesdf[['shape_id','shape_pt_lat','shape_pt_lon']])]

newnew

       shape_id  shape_pt_lat  shape_pt_lon
0        010058     42.373178    -71.118170
1        010058     42.373269    -71.118463
2        010058     42.373353    -71.118582
3        010058     42.373399    -71.118648
4        010058     42.373639    -71.118843
5        010058     42.373976    -71.118932
6        010058     42.374064    -71.118894
7        010058     42.374255    -71.118841
8        010058     42.374341    -71.118823
9        010058     42.374612    -71.118712
10       010058     42.375144    -71.118579
11       010058     42.375144    -71.118579
12       010058     42.375144    -71.118579
13       010058     42.375448    -71.118503
14       010058     42.375639    -71.118372
15       010058     42.375750    -71.118263
16       010058     42.375816    -71.118140
17       010058     42.375879    -71.118005
18       010058     42.375906    -71.117843
19       010058     42.375915    -71.117657
20       010058     42.375904    -71.117588
21       010058     42.375624    -71.116214
22       010058     42.375584    -71.115950
23       010058     42.375502    -71.115640
24       010058     42.375293    -71.115239
25       010058     42.375074    -71.114926
26       010058     42.374820    -71.114463
27       010058     42.374674    -71.114506
28       010058     42.374674    -71.114506
29       010058     42.374267    -71.114627
...         ...           ...           ...
273211  7510024     42.335039    -71.078806
273212  7510024     42.334944    -71.078924
273213  7510024     42.334944    -71.078924
273214  7510024     42.334624    -71.079320
273215  7510024     42.334584    -71.079363
273216  7510024     42.334258    -71.079828
273217  7510024     42.334178    -71.079943
273218  7510024     42.333987    -71.080188
273219  7510024     42.333760    -71.080453
273220  7510024     42.333632    -71.080582
273221  7510024     42.333517    -71.080680
273222  7510024     42.332965    -71.081077
273223  7510024     42.332898    -71.081127
273224  7510024     42.332768    -71.081185
273225  7510024     42.332768    -71.081185
273226  7510024     42.332539    -71.081273
273227  7510024     42.332274    -71.081414
273228  7510024     42.331940    -71.081717
273229  7510024     42.331752    -71.081934
273230  7510024     42.331371    -71.082372
273231  7510024     42.331055    -71.082716
273232  7510024     42.330817    -71.082987
273233  7510024     42.330665    -71.083201
273234  7510024     42.330586    -71.083344
273235  7510024     42.330455    -71.083721
273236  7510024     42.330300    -71.084053
273237  7510024     42.330174    -71.084217
273238  7510024     42.330063    -71.084324
273239  7510024     42.329905    -71.084446
273240  7510024     42.329848    -71.083876

[549 rows x 3 columns]

In [58]:
newnew.to_csv('MBTA_GTFS_csv/RouteShapes.csv',index=False)