In [1]:
import pandas as pd

In [2]:
shapesdf = pd.read_csv("MBTA_GTFS_csv/shapes.csv")

shapes = pd.DataFrame(shapesdf).drop(columns='Unnamed: 0')

In [9]:
trips = pd.read_csv("MBTA_GTFS_csv/trips.csv")

/Users/arimayer/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [10]:
routes = pd.read_csv("MBTA_GTFS_csv/routes.csv")

In [12]:
stops = pd.read_csv("MBTA_GTfS_csv/stops.csv")

In [3]:
#Route 1 line with its coinciding shapeID (one direction)
filter1 = shapes['shape_id']=='010058'

#Route 43 with its coinciding shapeID (one direction)
filter2 = shapes['shape_id']=='430031'

#Route SL5 with its coinciding shapeID (one direction)
filter3 = shapes['shape_id']=='7490022'

#Route SL4 with its coinciding shapeID (one direction)
filter4 = shapes['shape_id']=='7510024'

#Route 1 line with another coinciding shapeID (second direction)
filter5 = shapes['shape_id']=='010070'

#Route 43 line with another coinciding shapeID (second direction)
filter6 = shapes['shape_id']=='430029'

#Route SL5 line with another coinciding shapeID (second direction)
filter7 = shapes['shape_id']=='7490023'

#Route SL4 line with another coinciding shapeID (second direction)
filter8 = shapes['shape_id']=='7510025'

In [4]:
shapes.where(filter1 | filter2 | filter3 | filter4 |filter5 | filter6 | filter7 | filter8, inplace = True)

In [6]:
newshapesdf = shapes[['shape_id','shape_pt_lat','shape_pt_lon']].dropna()
newnew = newshapesdf[pd.notnull(newshapesdf[['shape_id','shape_pt_lat','shape_pt_lon']])]

newnew

       shape_id  shape_pt_lat  shape_pt_lon
0        010058     42.373178    -71.118170
1        010058     42.373269    -71.118463
2        010058     42.373353    -71.118582
3        010058     42.373399    -71.118648
4        010058     42.373639    -71.118843
5        010058     42.373976    -71.118932
6        010058     42.374064    -71.118894
7        010058     42.374255    -71.118841
8        010058     42.374341    -71.118823
9        010058     42.374612    -71.118712
10       010058     42.375144    -71.118579
11       010058     42.375144    -71.118579
12       010058     42.375144    -71.118579
13       010058     42.375448    -71.118503
14       010058     42.375639    -71.118372
15       010058     42.375750    -71.118263
16       010058     42.375816    -71.118140
17       010058     42.375879    -71.118005
18       010058     42.375906    -71.117843
19       010058     42.375915    -71.117657
20       010058     42.375904    -71.117588
21       010058     42.375624    -71.116214
22       010058     42.375584    -71.115950
23       010058     42.375502    -71.115640
24       010058     42.375293    -71.115239
25       010058     42.375074    -71.114926
26       010058     42.374820    -71.114463
27       010058     42.374674    -71.114506
28       010058     42.374674    -71.114506
29       010058     42.374267    -71.114627
...         ...           ...           ...
273317  7510025     42.347808    -71.064298
273318  7510025     42.348391    -71.064151
273319  7510025     42.349065    -71.063960
273320  7510025     42.349441    -71.063824
273321  7510025     42.350004    -71.063534
273322  7510025     42.350004    -71.063534
273323  7510025     42.350423    -71.063318
273324  7510025     42.350622    -71.063193
273325  7510025     42.350909    -71.063041
273326  7510025     42.351112    -71.062955
273327  7510025     42.351480    -71.062830
273328  7510025     42.351583    -71.062795
273329  7510025     42.351902    -71.062714
273330  7510025     42.352293    -71.062619
273331  7510025     42.352293    -71.062619
273332  7510025     42.352386    -71.062596
273333  7510025     42.352394    -71.062414
273334  7510025     42.352422    -71.062042
273335  7510025     42.352433    -71.061912
273336  7510025     42.352470    -71.061426
273337  7510025     42.352494    -71.061143
273338  7510025     42.352535    -71.060667
273339  7510025     42.352544    -71.060120
273340  7510025     42.352535    -71.059829
273341  7510025     42.352499    -71.059398
273342  7510025     42.352410    -71.058637
273343  7510025     42.352337    -71.058010
273344  7510025     42.352091    -71.057142
273345  7510025     42.352050    -71.056763
273346  7510025     42.351842    -71.055964

[1081 rows x 3 columns]

In [7]:
newnew.to_csv('MBTA_GTFS_csv/RouteShapes.csv',index=False)